name: Selenium tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  check_selenium_tests:
    runs-on: self-hosted
    timeout-minutes: 10
    container: 
      image: kel.osll.ru:8083/docker/ubuntu:selenium-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest
      env:
        HOME: /root
      run: |
         pip install -r requirements.txt
         pytest-3 main.py
      shell: bash
